### ISSUE TITLE
cannot build: hard-coded paths reference code not in this repository

### ISSUE THREAD

**Issue by swharden** [julihirn/Serial-Monitor#2]
The solution file cannot be built because of this line:

https://github.com/julihirn/Serial-Monitor/blob/0000a8fd94487c68142ee19ed1c3c9f9edd0d820/Serial%20Monitor.sln#L8

The readme notes that these modules are required, but provides no information about where to obtain them:

https://github.com/julihirn/Serial-Monitor/blob/0000a8fd94487c68142ee19ed1c3c9f9edd0d820/README.md?plain=1#L37-L38

Update: The missing code is here https://github.com/julihirn/ODModules

I highly recommend publishing that project as a NuGet package, then it can be easily used in other projects

**Comment by swharden** [comment]
This line is also very problematic. My computer does not have an E drive 😅 

https://github.com/julihirn/Serial-Monitor/blob/0000a8fd94487c68142ee19ed1c3c9f9edd0d820/Serial%20Monitor/Serial%20Monitor.csproj#L28

**Comment by julihirn** [comment]
These should all be fixed now. :) Updated the missing project files to the latest Nuget releases. Project Icon has been reassigned.
